In [17]:
import pandas as pd
df = pd.read_csv("atusact-clean.csv")
df.head()

,Unnamed: 0,tucaseid,tuactivity_n,tuactdur24,tustarttim,tustoptime,trcodep,trtier1p,trtier2p,tucumdur,tucumdur24,tuactdur
0,0,20030100013280,1,60,04:00:00,05:00:00,130124,13,1301,60,60,60
1,1,20030100013280,2,30,05:00:00,05:30:00,10201,1,102,90,90,30
2,2,20030100013280,3,600,05:30:00,15:30:00,10101,1,101,690,690,600
3,3,20030100013280,4,150,15:30:00,18:00:00,120303,12,1203,840,840,150
4,4,20030100013280,5,5,18:00:00,18:05:00,110101,11,1101,845,845,5

In [18]:
# Only keep rows where activity belongs to category we care about
"""Categories:
* Socializing
    * 1201
    * 1202
    * 1299
* Eating and Drinking
    * 11
* Household Activities
    * 02
* Consumer
    * 07
* Family Care
    * 03
* Work
    * 05
* Education
    * 06
* Sleeping
    * 0101
* TV/Games
    * 1203
    * 1204
* Sports/Exercise
    * 1301
    * 1399
"""
df = df[(df['trtier2p'] == 1201) | (df['trtier2p'] == 1202) | (df['trtier2p'] == 1203) | (df['trtier2p'] == 1204) | (df['trtier2p'] == 1299) | (df['trtier2p'] == 1301) | (df['trtier2p'] == 1399) | (df['trtier2p'] == 101) | (df['trtier1p'] == 11) | (df['trtier1p'] == 2) | (df['trtier1p'] == 3) | (df['trtier1p'] == 5) | (df['trtier1p'] == 6) | (df['trtier1p'] == 7)]
df

,Unnamed: 0,tucaseid,tuactivity_n,tuactdur24,tustarttim,tustoptime,trcodep,trtier1p,trtier2p,tucumdur,tucumdur24,tuactdur
0,0,20030100013280,1,60,04:00:00,05:00:00,130124,13,1301,60,60,60
2,2,20030100013280,3,600,05:30:00,15:30:00,10101,1,101,690,690,600
3,3,20030100013280,4,150,15:30:00,18:00:00,120303,12,1203,840,840,150
4,4,20030100013280,5,5,18:00:00,18:05:00,110101,11,1101,845,845,5
5,5,20030100013280,6,175,18:05:00,21:00:00,120303,12,1203,1020,1020,175
6,6,20030100013280,7,270,21:00:00,01:30:00,10101,1,101,1290,1290,270
8,8,20030100013280,9,140,01:40:00,04:30:00,130124,13,1301,1470,1440,170
9,9,20030100013344,1,180,04:00:00,07:00:00,10101,1,101,180,180,180
10,10,20030100013344,2,60,07:00:00,08:00:00,110101,11,1101,240,240,60
12,12,20030100013344,4,60,09:00:00,10:00:00,30101,3,301,360,360,60
14,14,20030100013344,6,530,10:10:00,19:00:00,120101,12,1201,900,900,530
16,16,20030100013344,8,30,19:10:00,19:40:00,110101,11,1101,940,940,30
17,17,20030100013344,9,60,19:40:00,20:40:00,120303,12,1203,1000,1000,60
18,18,20030100013344,10,440,20:40:00,07:00:00,10101,1,101,1620,1440,620
19,19,20030100013352,1,300,04:00:00,09:00:00,10101,1,101,300,300,300
21,21,20030100013352,3,30,10:00:00,10:30:00,110101,11,1101,390,390,30
23,23,20030100013352,5,60,10:35:00,11:35:00,70101,7,701,455,455,60
25,25,20030100013352,7,15,11:40:00,11:55:00,20104,2,201,475,475,15
26,26,20030100013352,8,120,11:55:00,13:55:00,120303,12,1203,595,595,120
28,28,20030100013352,10,180,14:55:00,17:55:00,20201,2,202,835,835,180
29,29,20030100013352,11,40,17:55:00,18:35:00,120101,12,1201,875,875,40
30,30,20030100013352,12,45,18:35:00,19:20:00,110101,11,1101,920,920,45
31,31,20030100013352,13,180,19:20:00,22:20:00,120101,12,1201,1100,1100,180
32,32,20030100013352,14,60,22:20:00,23:20:00,20203,2,202,1160,1160,60
34,34,20030100013352,16,260,23:40:00,09:45:00,10101,1,101,1785,1440,605
35,35,20030100013848,1,360,04:00:00,10:00:00,10101,1,101,360,360,360
36,36,20030100013848,2,20,10:00:00,10:20:00,20201,2,202,380,380,20
37,37,20030100013848,3,5,10:20:00,10:25:00,30101,3,301,385,385,5
38,38,20030100013848,4,15,10:25:00,10:40:00,20203,2,202,400,400,15
40,40,20030100013848,6,10,11:00:00,11:10:00,20681,2,206,430,430,10
...,...,...,...,...,...,...,...,...,...,...,...,...
3347050,3347050,20151212152477,6,60,17:00:00,18:00:00,110101,11,1101,840,840,60
3347051,3347051,20151212152477,7,90,18:00:00,19:30:00,10101,1,101,930,930,90
3347052,3347052,20151212152477,8,120,19:30:00,21:30:00,120303,12,1203,1050,1050,120
3347054,3347054,20151212152477,10,2,22:00:00,22:02:00,30112,3,301,1082,1082,2
3347056,3347056,20151212152477,12,120,22:07:00,00:07:00,20101,2,201,1207,1207,120
3347058,3347058,20151212152477,14,15,00:22:00,00:37:00,110101,11,1101,1237,1237,15
3347059,3347059,20151212152477,15,143,00:37:00,03:00:00,120101,12,1201,1380,1380,143
3347061,3347061,20151212152477,17,45,03:15:00,04:00:00,120303,12,1203,1440,1440,45
3347062,3347062,20151212152498,1,120,04:00:00,06:00:00,10101,1,101,120,120,120
3347063,3347063,20151212152498,2,15,06:00:00,06:15:00,20201,2,202,135,135,15
3347064,3347064,20151212152498,3,5,06:15:00,06:20:00,20681,2,206,140,140,5
3347065,3347065,20151212152498,4,1,06:20:00,06:21:00,20681,2,206,141,141,1
3347066,3347066,20151212152498,5,1,06:21:00,06:22:00,20681,2,206,142,142,1
3347067,3347067,20151212152498,6,5,06:22:00,06:27:00,20201,2,202,147,147,5
3347068,3347068,20151212152498,7,60,06:27:00,07:27:00,120303,12,1203,207,207,60
3347069,3347069,20151212152498,8,60,07:27:00,08:27:00,120308,12,1203,267,267,60
3347070,3347070,20151212152498,9,60,08:27:00,09:27:00,120101,12,1201,327,327,60
3347072,3347072,20151212152498,11,93,09:57:00,11:30:00,120101,12,1201,450,450,93
3347074,3347074,20151212152498,13,120,13:00:00,15:00:00,120101,12,1201,660,660,120
3347076,3347076,20151212152498,15,10,15:05:00,15:15:00,70103,7,701,675,675,10
3347078,3347078,20151212152498,17,30,15:20:00,15:50:00,110101,11,1101,710,710,30
3347079,3347079,20151212152498,18,70,15:50:00,17:00:00,120101,12,1201,780,780,70
3347081,3347081,20151212152498,20,10,18:15:00,18:25:00,20902,2,209,865,865,10
3347083,3347083,20151212152498,22,10,18:27:00,18:37:00,20902,2,209,877,877,10
3347085,3347085,20151212152498,24,5,19:02:00,19:07:00,20681,2,206,907,907,5
3347086,3347086,20151212152498,25,25,19:07:00,19:32:00,20681,2,206,932,932,25
3347089,3347089,20151212152498,28,53,20:07:00,21:00:00,120101,12,1201,1020,1020,53
3347090,3347090,20151212152498,29,15,21:00:00,21:15:00,30101,3,301,1035,1035,15
3347091,3347091,20151212152498,30,165,21:15:00,00:00:00,120303,12,1203,1200,1200,165
3347092,3347092,20151212152498,31,240,00:00:00,07:30:00,10101,1,101,1650,1440,450

In [19]:
# further drop unused columns
df = df.drop(columns=['tuactdur24', 'trcodep', 'tucumdur', 'tucumdur24', 'Unnamed: 0'])
df

,tucaseid,tuactivity_n,tustarttim,tustoptime,trtier1p,trtier2p,tuactdur
0,20030100013280,1,04:00:00,05:00:00,13,1301,60
2,20030100013280,3,05:30:00,15:30:00,1,101,600
3,20030100013280,4,15:30:00,18:00:00,12,1203,150
4,20030100013280,5,18:00:00,18:05:00,11,1101,5
5,20030100013280,6,18:05:00,21:00:00,12,1203,175
6,20030100013280,7,21:00:00,01:30:00,1,101,270
8,20030100013280,9,01:40:00,04:30:00,13,1301,170
9,20030100013344,1,04:00:00,07:00:00,1,101,180
10,20030100013344,2,07:00:00,08:00:00,11,1101,60
12,20030100013344,4,09:00:00,10:00:00,3,301,60
14,20030100013344,6,10:10:00,19:00:00,12,1201,530
16,20030100013344,8,19:10:00,19:40:00,11,1101,30
17,20030100013344,9,19:40:00,20:40:00,12,1203,60
18,20030100013344,10,20:40:00,07:00:00,1,101,620
19,20030100013352,1,04:00:00,09:00:00,1,101,300
21,20030100013352,3,10:00:00,10:30:00,11,1101,30
23,20030100013352,5,10:35:00,11:35:00,7,701,60
25,20030100013352,7,11:40:00,11:55:00,2,201,15
26,20030100013352,8,11:55:00,13:55:00,12,1203,120
28,20030100013352,10,14:55:00,17:55:00,2,202,180
29,20030100013352,11,17:55:00,18:35:00,12,1201,40
30,20030100013352,12,18:35:00,19:20:00,11,1101,45
31,20030100013352,13,19:20:00,22:20:00,12,1201,180
32,20030100013352,14,22:20:00,23:20:00,2,202,60
34,20030100013352,16,23:40:00,09:45:00,1,101,605
35,20030100013848,1,04:00:00,10:00:00,1,101,360
36,20030100013848,2,10:00:00,10:20:00,2,202,20
37,20030100013848,3,10:20:00,10:25:00,3,301,5
38,20030100013848,4,10:25:00,10:40:00,2,202,15
40,20030100013848,6,11:00:00,11:10:00,2,206,10
...,...,...,...,...,...,...,...
3347050,20151212152477,6,17:00:00,18:00:00,11,1101,60
3347051,20151212152477,7,18:00:00,19:30:00,1,101,90
3347052,20151212152477,8,19:30:00,21:30:00,12,1203,120
3347054,20151212152477,10,22:00:00,22:02:00,3,301,2
3347056,20151212152477,12,22:07:00,00:07:00,2,201,120
3347058,20151212152477,14,00:22:00,00:37:00,11,1101,15
3347059,20151212152477,15,00:37:00,03:00:00,12,1201,143
3347061,20151212152477,17,03:15:00,04:00:00,12,1203,45
3347062,20151212152498,1,04:00:00,06:00:00,1,101,120
3347063,20151212152498,2,06:00:00,06:15:00,2,202,15
3347064,20151212152498,3,06:15:00,06:20:00,2,206,5
3347065,20151212152498,4,06:20:00,06:21:00,2,206,1
3347066,20151212152498,5,06:21:00,06:22:00,2,206,1
3347067,20151212152498,6,06:22:00,06:27:00,2,202,5
3347068,20151212152498,7,06:27:00,07:27:00,12,1203,60
3347069,20151212152498,8,07:27:00,08:27:00,12,1203,60
3347070,20151212152498,9,08:27:00,09:27:00,12,1201,60
3347072,20151212152498,11,09:57:00,11:30:00,12,1201,93
3347074,20151212152498,13,13:00:00,15:00:00,12,1201,120
3347076,20151212152498,15,15:05:00,15:15:00,7,701,10
3347078,20151212152498,17,15:20:00,15:50:00,11,1101,30
3347079,20151212152498,18,15:50:00,17:00:00,12,1201,70
3347081,20151212152498,20,18:15:00,18:25:00,2,209,10
3347083,20151212152498,22,18:27:00,18:37:00,2,209,10
3347085,20151212152498,24,19:02:00,19:07:00,2,206,5
3347086,20151212152498,25,19:07:00,19:32:00,2,206,25
3347089,20151212152498,28,20:07:00,21:00:00,12,1201,53
3347090,20151212152498,29,21:00:00,21:15:00,3,301,15
3347091,20151212152498,30,21:15:00,00:00:00,12,1203,165
3347092,20151212152498,31,00:00:00,07:30:00,1,101,450

In [20]:
# create new column with activitiy category (string)
def f(row):
    if row['trtier2p'] == 101:
        val = 'sleep'
    elif row['trtier1p'] == 2:
        val = 'household'
    elif row['trtier1p'] == 3:
        val = 'family'
    elif row['trtier1p'] == 5:
        val = 'work'
    elif row['trtier1p'] == 6:
        val = 'education'
    elif row['trtier1p'] == 7:
        val = 'shopping'
    elif row['trtier1p'] == 11:
        val = 'eating'
    elif (row['trtier2p'] == 1201) or (row['trtier2p'] == 1202) or (row['trtier2p'] == 1299):
        val = 'socializing'
    elif (row['trtier2p'] == 1203) or (row['trtier2p'] == 1204):
        val = 'entertainment'
    #elif row['trtier2p'] > 1300:
    else:
        val = 'sports'
    return val

df['category'] = df.apply(f, axis=1)
df

,tucaseid,tuactivity_n,tustarttim,tustoptime,trtier1p,trtier2p,tuactdur,category
0,20030100013280,1,04:00:00,05:00:00,13,1301,60,sports
2,20030100013280,3,05:30:00,15:30:00,1,101,600,sleep
3,20030100013280,4,15:30:00,18:00:00,12,1203,150,entertainment
4,20030100013280,5,18:00:00,18:05:00,11,1101,5,eating
5,20030100013280,6,18:05:00,21:00:00,12,1203,175,entertainment
6,20030100013280,7,21:00:00,01:30:00,1,101,270,sleep
8,20030100013280,9,01:40:00,04:30:00,13,1301,170,sports
9,20030100013344,1,04:00:00,07:00:00,1,101,180,sleep
10,20030100013344,2,07:00:00,08:00:00,11,1101,60,eating
12,20030100013344,4,09:00:00,10:00:00,3,301,60,family
14,20030100013344,6,10:10:00,19:00:00,12,1201,530,socializing
16,20030100013344,8,19:10:00,19:40:00,11,1101,30,eating
17,20030100013344,9,19:40:00,20:40:00,12,1203,60,entertainment
18,20030100013344,10,20:40:00,07:00:00,1,101,620,sleep
19,20030100013352,1,04:00:00,09:00:00,1,101,300,sleep
21,20030100013352,3,10:00:00,10:30:00,11,1101,30,eating
23,20030100013352,5,10:35:00,11:35:00,7,701,60,shopping
25,20030100013352,7,11:40:00,11:55:00,2,201,15,household
26,20030100013352,8,11:55:00,13:55:00,12,1203,120,entertainment
28,20030100013352,10,14:55:00,17:55:00,2,202,180,household
29,20030100013352,11,17:55:00,18:35:00,12,1201,40,socializing
30,20030100013352,12,18:35:00,19:20:00,11,1101,45,eating
31,20030100013352,13,19:20:00,22:20:00,12,1201,180,socializing
32,20030100013352,14,22:20:00,23:20:00,2,202,60,household
34,20030100013352,16,23:40:00,09:45:00,1,101,605,sleep
35,20030100013848,1,04:00:00,10:00:00,1,101,360,sleep
36,20030100013848,2,10:00:00,10:20:00,2,202,20,household
37,20030100013848,3,10:20:00,10:25:00,3,301,5,family
38,20030100013848,4,10:25:00,10:40:00,2,202,15,household
40,20030100013848,6,11:00:00,11:10:00,2,206,10,household
...,...,...,...,...,...,...,...,...
3347050,20151212152477,6,17:00:00,18:00:00,11,1101,60,eating
3347051,20151212152477,7,18:00:00,19:30:00,1,101,90,sleep
3347052,20151212152477,8,19:30:00,21:30:00,12,1203,120,entertainment
3347054,20151212152477,10,22:00:00,22:02:00,3,301,2,family
3347056,20151212152477,12,22:07:00,00:07:00,2,201,120,household
3347058,20151212152477,14,00:22:00,00:37:00,11,1101,15,eating
3347059,20151212152477,15,00:37:00,03:00:00,12,1201,143,socializing
3347061,20151212152477,17,03:15:00,04:00:00,12,1203,45,entertainment
3347062,20151212152498,1,04:00:00,06:00:00,1,101,120,sleep
3347063,20151212152498,2,06:00:00,06:15:00,2,202,15,household
3347064,20151212152498,3,06:15:00,06:20:00,2,206,5,household
3347065,20151212152498,4,06:20:00,06:21:00,2,206,1,household
3347066,20151212152498,5,06:21:00,06:22:00,2,206,1,household
3347067,20151212152498,6,06:22:00,06:27:00,2,202,5,household
3347068,20151212152498,7,06:27:00,07:27:00,12,1203,60,entertainment
3347069,20151212152498,8,07:27:00,08:27:00,12,1203,60,entertainment
3347070,20151212152498,9,08:27:00,09:27:00,12,1201,60,socializing
3347072,20151212152498,11,09:57:00,11:30:00,12,1201,93,socializing
3347074,20151212152498,13,13:00:00,15:00:00,12,1201,120,socializing
3347076,20151212152498,15,15:05:00,15:15:00,7,701,10,shopping
3347078,20151212152498,17,15:20:00,15:50:00,11,1101,30,eating
3347079,20151212152498,18,15:50:00,17:00:00,12,1201,70,socializing
3347081,20151212152498,20,18:15:00,18:25:00,2,209,10,household
3347083,20151212152498,22,18:27:00,18:37:00,2,209,10,household
3347085,20151212152498,24,19:02:00,19:07:00,2,206,5,household
3347086,20151212152498,25,19:07:00,19:32:00,2,206,25,household
3347089,20151212152498,28,20:07:00,21:00:00,12,1201,53,socializing
3347090,20151212152498,29,21:00:00,21:15:00,3,301,15,family
3347091,20151212152498,30,21:15:00,00:00:00,12,1203,165,entertainment
3347092,20151212152498,31,00:00:00,07:30:00,1,101,450,sleep

In [21]:
df = df.drop(columns=['tuactivity_n', 'trtier1p', 'trtier2p'])
df

               tucaseid tustarttim tustoptime  tuactdur       category
0        20030100013280   04:00:00   05:00:00        60         sports
2        20030100013280   05:30:00   15:30:00       600          sleep
3        20030100013280   15:30:00   18:00:00       150  entertainment
4        20030100013280   18:00:00   18:05:00         5         eating
5        20030100013280   18:05:00   21:00:00       175  entertainment
6        20030100013280   21:00:00   01:30:00       270          sleep
8        20030100013280   01:40:00   04:30:00       170         sports
9        20030100013344   04:00:00   07:00:00       180          sleep
10       20030100013344   07:00:00   08:00:00        60         eating
12       20030100013344   09:00:00   10:00:00        60         family
14       20030100013344   10:10:00   19:00:00       530    socializing
16       20030100013344   19:10:00   19:40:00        30         eating
17       20030100013344   19:40:00   20:40:00        60  entertainment
18       20030100013344   20:40:00   07:00:00       620          sleep
19       20030100013352   04:00:00   09:00:00       300          sleep
21       20030100013352   10:00:00   10:30:00        30         eating
23       20030100013352   10:35:00   11:35:00        60       shopping
25       20030100013352   11:40:00   11:55:00        15      household
26       20030100013352   11:55:00   13:55:00       120  entertainment
28       20030100013352   14:55:00   17:55:00       180      household
29       20030100013352   17:55:00   18:35:00        40    socializing
30       20030100013352   18:35:00   19:20:00        45         eating
31       20030100013352   19:20:00   22:20:00       180    socializing
32       20030100013352   22:20:00   23:20:00        60      household
34       20030100013352   23:40:00   09:45:00       605          sleep
35       20030100013848   04:00:00   10:00:00       360          sleep
36       20030100013848   10:00:00   10:20:00        20      household
37       20030100013848   10:20:00   10:25:00         5         family
38       20030100013848   10:25:00   10:40:00        15      household
40       20030100013848   11:00:00   11:10:00        10      household
...                 ...        ...        ...       ...            ...
3347050  20151212152477   17:00:00   18:00:00        60         eating
3347051  20151212152477   18:00:00   19:30:00        90          sleep
3347052  20151212152477   19:30:00   21:30:00       120  entertainment
3347054  20151212152477   22:00:00   22:02:00         2         family
3347056  20151212152477   22:07:00   00:07:00       120      household
3347058  20151212152477   00:22:00   00:37:00        15         eating
3347059  20151212152477   00:37:00   03:00:00       143    socializing
3347061  20151212152477   03:15:00   04:00:00        45  entertainment
3347062  20151212152498   04:00:00   06:00:00       120          sleep
3347063  20151212152498   06:00:00   06:15:00        15      household
3347064  20151212152498   06:15:00   06:20:00         5      household
3347065  20151212152498   06:20:00   06:21:00         1      household
3347066  20151212152498   06:21:00   06:22:00         1      household
3347067  20151212152498   06:22:00   06:27:00         5      household
3347068  20151212152498   06:27:00   07:27:00        60  entertainment
3347069  20151212152498   07:27:00   08:27:00        60  entertainment
3347070  20151212152498   08:27:00   09:27:00        60    socializing
3347072  20151212152498   09:57:00   11:30:00        93    socializing
3347074  20151212152498   13:00:00   15:00:00       120    socializing
3347076  20151212152498   15:05:00   15:15:00        10       shopping
3347078  20151212152498   15:20:00   15:50:00        30         eating
3347079  20151212152498   15:50:00   17:00:00        70    socializing
3347081  20151212152498   18:15:00   18:25:00        10      household
3347083  20151212152498   18:27:00   18:37:00        10      household
3347085  20151212152498   19:02:00   19:07:00         5      household
3347086  20151212152498   19:07:00   19:32:00        25      household
3347089  20151212152498   20:07:00   21:00:00        53    socializing
3347090  20151212152498   21:00:00   21:15:00        15         family
3347091  20151212152498   21:15:00   00:00:00       165  entertainment
3347092  20151212152498   00:00:00   07:30:00       450          sleep

[2240579 rows x 5 columns]

In [22]:
cps = pd.read_csv("atuscps-cleaned-again.csv")
cps = cps.drop(columns=['Unnamed: 0'])
cps

              tucaseid  hefaminc
0       20030100013007         0
1       20030100013013         0
2       20030100013014         1
3       20030100013017         0
4       20030100013030         0
5       20030100013050         0
6       20030100013109         1
7       20030100013125         0
8       20030100013158         0
9       20030100013166         1
10      20030100013167         0
11      20030100013169         0
12      20030100013189         1
13      20030100013208         0
14      20030100013229         1
15      20030100013232         1
16      20030100013280         1
17      20030100013284         0
18      20030100013291         0
19      20030100013300         0
20      20030100013304         0
21      20030100013327         1
22      20030100013330         1
23      20030100013337         1
24      20030100013347         1
25      20030100013352         1
26      20030100013394         0
27      20030100013396         1
28      20030100013414         0
29      20030100013420         0
...                ...       ...
305017  20151212151459         0
305018  20151212151497         0
305019  20151212151542         1
305020  20151212151559         1
305021  20151212151560         2
305022  20151212151571         0
305023  20151212151682         3
305024  20151212151686         0
305025  20151212151694         1
305026  20151212151707         3
305027  20151212151875         0
305028  20151212151885         0
305029  20151212151886         2
305030  20151212151905         0
305031  20151212151939         3
305032  20151212151940         3
305033  20151212151960         0
305034  20151212151989         1
305035  20151212152019         2
305036  20151212152025         2
305037  20151212152031         0
305038  20151212152152         1
305039  20151212152155         0
305040  20151212152219         1
305041  20151212152375         2
305042  20151212152399         1
305043  20151212152468         3
305044  20151212152469         0
305045  20151212152477         1
305046  20151212152498         0

[305047 rows x 2 columns]

In [23]:
merge = pd.merge(df, cps, on='tucaseid')
merge

,tucaseid,tustarttim,tustoptime,tuactdur,category,hefaminc
0,20030100013280,04:00:00,05:00:00,60,sports,1
1,20030100013280,05:30:00,15:30:00,600,sleep,1
2,20030100013280,15:30:00,18:00:00,150,entertainment,1
3,20030100013280,18:00:00,18:05:00,5,eating,1
4,20030100013280,18:05:00,21:00:00,175,entertainment,1
5,20030100013280,21:00:00,01:30:00,270,sleep,1
6,20030100013280,01:40:00,04:30:00,170,sports,1
7,20030100013352,04:00:00,09:00:00,300,sleep,1
8,20030100013352,10:00:00,10:30:00,30,eating,1
9,20030100013352,10:35:00,11:35:00,60,shopping,1
10,20030100013352,11:40:00,11:55:00,15,household,1
11,20030100013352,11:55:00,13:55:00,120,entertainment,1
12,20030100013352,14:55:00,17:55:00,180,household,1
13,20030100013352,17:55:00,18:35:00,40,socializing,1
14,20030100013352,18:35:00,19:20:00,45,eating,1
15,20030100013352,19:20:00,22:20:00,180,socializing,1
16,20030100013352,22:20:00,23:20:00,60,household,1
17,20030100013352,23:40:00,09:45:00,605,sleep,1
18,20030100013848,04:00:00,10:00:00,360,sleep,0
19,20030100013848,10:00:00,10:20:00,20,household,0
20,20030100013848,10:20:00,10:25:00,5,family,0
21,20030100013848,10:25:00,10:40:00,15,household,0
22,20030100013848,11:00:00,11:10:00,10,household,0
23,20030100013848,11:10:00,13:10:00,120,work,0
24,20030100013848,13:10:00,15:00:00,110,household,0
25,20030100013848,15:00:00,16:15:00,75,household,0
26,20030100013848,16:15:00,17:30:00,75,sleep,0
27,20030100013848,17:30:00,17:45:00,15,household,0
28,20030100013848,17:45:00,18:10:00,25,eating,0
29,20030100013848,18:10:00,18:35:00,25,household,0
...,...,...,...,...,...,...
2064734,20151212152477,17:00:00,18:00:00,60,eating,1
2064735,20151212152477,18:00:00,19:30:00,90,sleep,1
2064736,20151212152477,19:30:00,21:30:00,120,entertainment,1
2064737,20151212152477,22:00:00,22:02:00,2,family,1
2064738,20151212152477,22:07:00,00:07:00,120,household,1
2064739,20151212152477,00:22:00,00:37:00,15,eating,1
2064740,20151212152477,00:37:00,03:00:00,143,socializing,1
2064741,20151212152477,03:15:00,04:00:00,45,entertainment,1
2064742,20151212152498,04:00:00,06:00:00,120,sleep,0
2064743,20151212152498,06:00:00,06:15:00,15,household,0
2064744,20151212152498,06:15:00,06:20:00,5,household,0
2064745,20151212152498,06:20:00,06:21:00,1,household,0
2064746,20151212152498,06:21:00,06:22:00,1,household,0
2064747,20151212152498,06:22:00,06:27:00,5,household,0
2064748,20151212152498,06:27:00,07:27:00,60,entertainment,0
2064749,20151212152498,07:27:00,08:27:00,60,entertainment,0
2064750,20151212152498,08:27:00,09:27:00,60,socializing,0
2064751,20151212152498,09:57:00,11:30:00,93,socializing,0
2064752,20151212152498,13:00:00,15:00:00,120,socializing,0
2064753,20151212152498,15:05:00,15:15:00,10,shopping,0
2064754,20151212152498,15:20:00,15:50:00,30,eating,0
2064755,20151212152498,15:50:00,17:00:00,70,socializing,0
2064756,20151212152498,18:15:00,18:25:00,10,household,0
2064757,20151212152498,18:27:00,18:37:00,10,household,0
2064758,20151212152498,19:02:00,19:07:00,5,household,0
2064759,20151212152498,19:07:00,19:32:00,25,household,0
2064760,20151212152498,20:07:00,21:00:00,53,socializing,0
2064761,20151212152498,21:00:00,21:15:00,15,family,0
2064762,20151212152498,21:15:00,00:00:00,165,entertainment,0
2064763,20151212152498,00:00:00,07:30:00,450,sleep,0

In [24]:
merge.columns = ['id','stime','etime', 'duration','category','income']
merge

                     id     stime     etime  duration       category  income
0        20030100013280  04:00:00  05:00:00        60         sports       1
1        20030100013280  05:30:00  15:30:00       600          sleep       1
2        20030100013280  15:30:00  18:00:00       150  entertainment       1
3        20030100013280  18:00:00  18:05:00         5         eating       1
4        20030100013280  18:05:00  21:00:00       175  entertainment       1
5        20030100013280  21:00:00  01:30:00       270          sleep       1
6        20030100013280  01:40:00  04:30:00       170         sports       1
7        20030100013352  04:00:00  09:00:00       300          sleep       1
8        20030100013352  10:00:00  10:30:00        30         eating       1
9        20030100013352  10:35:00  11:35:00        60       shopping       1
10       20030100013352  11:40:00  11:55:00        15      household       1
11       20030100013352  11:55:00  13:55:00       120  entertainment       1
12       20030100013352  14:55:00  17:55:00       180      household       1
13       20030100013352  17:55:00  18:35:00        40    socializing       1
14       20030100013352  18:35:00  19:20:00        45         eating       1
15       20030100013352  19:20:00  22:20:00       180    socializing       1
16       20030100013352  22:20:00  23:20:00        60      household       1
17       20030100013352  23:40:00  09:45:00       605          sleep       1
18       20030100013848  04:00:00  10:00:00       360          sleep       0
19       20030100013848  10:00:00  10:20:00        20      household       0
20       20030100013848  10:20:00  10:25:00         5         family       0
21       20030100013848  10:25:00  10:40:00        15      household       0
22       20030100013848  11:00:00  11:10:00        10      household       0
23       20030100013848  11:10:00  13:10:00       120           work       0
24       20030100013848  13:10:00  15:00:00       110      household       0
25       20030100013848  15:00:00  16:15:00        75      household       0
26       20030100013848  16:15:00  17:30:00        75          sleep       0
27       20030100013848  17:30:00  17:45:00        15      household       0
28       20030100013848  17:45:00  18:10:00        25         eating       0
29       20030100013848  18:10:00  18:35:00        25      household       0
...                 ...       ...       ...       ...            ...     ...
2064734  20151212152477  17:00:00  18:00:00        60         eating       1
2064735  20151212152477  18:00:00  19:30:00        90          sleep       1
2064736  20151212152477  19:30:00  21:30:00       120  entertainment       1
2064737  20151212152477  22:00:00  22:02:00         2         family       1
2064738  20151212152477  22:07:00  00:07:00       120      household       1
2064739  20151212152477  00:22:00  00:37:00        15         eating       1
2064740  20151212152477  00:37:00  03:00:00       143    socializing       1
2064741  20151212152477  03:15:00  04:00:00        45  entertainment       1
2064742  20151212152498  04:00:00  06:00:00       120          sleep       0
2064743  20151212152498  06:00:00  06:15:00        15      household       0
2064744  20151212152498  06:15:00  06:20:00         5      household       0
2064745  20151212152498  06:20:00  06:21:00         1      household       0
2064746  20151212152498  06:21:00  06:22:00         1      household       0
2064747  20151212152498  06:22:00  06:27:00         5      household       0
2064748  20151212152498  06:27:00  07:27:00        60  entertainment       0
2064749  20151212152498  07:27:00  08:27:00        60  entertainment       0
2064750  20151212152498  08:27:00  09:27:00        60    socializing       0
2064751  20151212152498  09:57:00  11:30:00        93    socializing       0
2064752  20151212152498  13:00:00  15:00:00       120    socializing       0
2064753  20151212152498  15:05:00  15:15:00        10       shopping       0
2064754  20151212152498  15:20:00  15:50:00        30         eating       0
2064755  20151212152498  15:50:00  17:00:00        70    socializing       0
2064756  20151212152498  18:15:00  18:25:00        10      household       0
2064757  20151212152498  18:27:00  18:37:00        10      household       0
2064758  20151212152498  19:02:00  19:07:00         5      household       0
2064759  20151212152498  19:07:00  19:32:00        25      household       0
2064760  20151212152498  20:07:00  21:00:00        53    socializing       0
2064761  20151212152498  21:00:00  21:15:00        15         family       0
2064762  20151212152498  21:15:00  00:00:00       165  entertainment       0
2064763  20151212152498  00:00:00  07:30:00       450          sleep       0

[2064764 rows x 6 columns]

In [25]:
time = pd.DatetimeIndex(merge['stime'])
merge['start'] = time.hour * 60 + time.minute

time = pd.DatetimeIndex(merge['etime'])
merge['end'] = time.hour * 60 + time.minute

merge

,id,stime,etime,duration,category,income,start,end
0,20030100013280,04:00:00,05:00:00,60,sports,1,240,300
1,20030100013280,05:30:00,15:30:00,600,sleep,1,330,930
2,20030100013280,15:30:00,18:00:00,150,entertainment,1,930,1080
3,20030100013280,18:00:00,18:05:00,5,eating,1,1080,1085
4,20030100013280,18:05:00,21:00:00,175,entertainment,1,1085,1260
5,20030100013280,21:00:00,01:30:00,270,sleep,1,1260,90
6,20030100013280,01:40:00,04:30:00,170,sports,1,100,270
7,20030100013352,04:00:00,09:00:00,300,sleep,1,240,540
8,20030100013352,10:00:00,10:30:00,30,eating,1,600,630
9,20030100013352,10:35:00,11:35:00,60,shopping,1,635,695
10,20030100013352,11:40:00,11:55:00,15,household,1,700,715
11,20030100013352,11:55:00,13:55:00,120,entertainment,1,715,835
12,20030100013352,14:55:00,17:55:00,180,household,1,895,1075
13,20030100013352,17:55:00,18:35:00,40,socializing,1,1075,1115
14,20030100013352,18:35:00,19:20:00,45,eating,1,1115,1160
15,20030100013352,19:20:00,22:20:00,180,socializing,1,1160,1340
16,20030100013352,22:20:00,23:20:00,60,household,1,1340,1400
17,20030100013352,23:40:00,09:45:00,605,sleep,1,1420,585
18,20030100013848,04:00:00,10:00:00,360,sleep,0,240,600
19,20030100013848,10:00:00,10:20:00,20,household,0,600,620
20,20030100013848,10:20:00,10:25:00,5,family,0,620,625
21,20030100013848,10:25:00,10:40:00,15,household,0,625,640
22,20030100013848,11:00:00,11:10:00,10,household,0,660,670
23,20030100013848,11:10:00,13:10:00,120,work,0,670,790
24,20030100013848,13:10:00,15:00:00,110,household,0,790,900
25,20030100013848,15:00:00,16:15:00,75,household,0,900,975
26,20030100013848,16:15:00,17:30:00,75,sleep,0,975,1050
27,20030100013848,17:30:00,17:45:00,15,household,0,1050,1065
28,20030100013848,17:45:00,18:10:00,25,eating,0,1065,1090
29,20030100013848,18:10:00,18:35:00,25,household,0,1090,1115
...,...,...,...,...,...,...,...,...
2064734,20151212152477,17:00:00,18:00:00,60,eating,1,1020,1080
2064735,20151212152477,18:00:00,19:30:00,90,sleep,1,1080,1170
2064736,20151212152477,19:30:00,21:30:00,120,entertainment,1,1170,1290
2064737,20151212152477,22:00:00,22:02:00,2,family,1,1320,1322
2064738,20151212152477,22:07:00,00:07:00,120,household,1,1327,7
2064739,20151212152477,00:22:00,00:37:00,15,eating,1,22,37
2064740,20151212152477,00:37:00,03:00:00,143,socializing,1,37,180
2064741,20151212152477,03:15:00,04:00:00,45,entertainment,1,195,240
2064742,20151212152498,04:00:00,06:00:00,120,sleep,0,240,360
2064743,20151212152498,06:00:00,06:15:00,15,household,0,360,375
2064744,20151212152498,06:15:00,06:20:00,5,household,0,375,380
2064745,20151212152498,06:20:00,06:21:00,1,household,0,380,381
2064746,20151212152498,06:21:00,06:22:00,1,household,0,381,382
2064747,20151212152498,06:22:00,06:27:00,5,household,0,382,387
2064748,20151212152498,06:27:00,07:27:00,60,entertainment,0,387,447
2064749,20151212152498,07:27:00,08:27:00,60,entertainment,0,447,507
2064750,20151212152498,08:27:00,09:27:00,60,socializing,0,507,567
2064751,20151212152498,09:57:00,11:30:00,93,socializing,0,597,690
2064752,20151212152498,13:00:00,15:00:00,120,socializing,0,780,900
2064753,20151212152498,15:05:00,15:15:00,10,shopping,0,905,915
2064754,20151212152498,15:20:00,15:50:00,30,eating,0,920,950
2064755,20151212152498,15:50:00,17:00:00,70,socializing,0,950,1020
2064756,20151212152498,18:15:00,18:25:00,10,household,0,1095,1105
2064757,20151212152498,18:27:00,18:37:00,10,household,0,1107,1117
2064758,20151212152498,19:02:00,19:07:00,5,household,0,1142,1147
2064759,20151212152498,19:07:00,19:32:00,25,household,0,1147,1172
2064760,20151212152498,20:07:00,21:00:00,53,socializing,0,1207,1260
2064761,20151212152498,21:00:00,21:15:00,15,family,0,1260,1275
2064762,20151212152498,21:15:00,00:00:00,165,entertainment,0,1275,0
2064763,20151212152498,00:00:00,07:30:00,450,sleep,0,0,450

In [26]:
merge = merge.drop(columns=['stime', 'etime'])
merge

                     id  duration       category  income  start   end
0        20030100013280        60         sports       1    240   300
1        20030100013280       600          sleep       1    330   930
2        20030100013280       150  entertainment       1    930  1080
3        20030100013280         5         eating       1   1080  1085
4        20030100013280       175  entertainment       1   1085  1260
5        20030100013280       270          sleep       1   1260    90
6        20030100013280       170         sports       1    100   270
7        20030100013352       300          sleep       1    240   540
8        20030100013352        30         eating       1    600   630
9        20030100013352        60       shopping       1    635   695
10       20030100013352        15      household       1    700   715
11       20030100013352       120  entertainment       1    715   835
12       20030100013352       180      household       1    895  1075
13       20030100013352        40    socializing       1   1075  1115
14       20030100013352        45         eating       1   1115  1160
15       20030100013352       180    socializing       1   1160  1340
16       20030100013352        60      household       1   1340  1400
17       20030100013352       605          sleep       1   1420   585
18       20030100013848       360          sleep       0    240   600
19       20030100013848        20      household       0    600   620
20       20030100013848         5         family       0    620   625
21       20030100013848        15      household       0    625   640
22       20030100013848        10      household       0    660   670
23       20030100013848       120           work       0    670   790
24       20030100013848       110      household       0    790   900
25       20030100013848        75      household       0    900   975
26       20030100013848        75          sleep       0    975  1050
27       20030100013848        15      household       0   1050  1065
28       20030100013848        25         eating       0   1065  1090
29       20030100013848        25      household       0   1090  1115
...                 ...       ...            ...     ...    ...   ...
2064734  20151212152477        60         eating       1   1020  1080
2064735  20151212152477        90          sleep       1   1080  1170
2064736  20151212152477       120  entertainment       1   1170  1290
2064737  20151212152477         2         family       1   1320  1322
2064738  20151212152477       120      household       1   1327     7
2064739  20151212152477        15         eating       1     22    37
2064740  20151212152477       143    socializing       1     37   180
2064741  20151212152477        45  entertainment       1    195   240
2064742  20151212152498       120          sleep       0    240   360
2064743  20151212152498        15      household       0    360   375
2064744  20151212152498         5      household       0    375   380
2064745  20151212152498         1      household       0    380   381
2064746  20151212152498         1      household       0    381   382
2064747  20151212152498         5      household       0    382   387
2064748  20151212152498        60  entertainment       0    387   447
2064749  20151212152498        60  entertainment       0    447   507
2064750  20151212152498        60    socializing       0    507   567
2064751  20151212152498        93    socializing       0    597   690
2064752  20151212152498       120    socializing       0    780   900
2064753  20151212152498        10       shopping       0    905   915
2064754  20151212152498        30         eating       0    920   950
2064755  20151212152498        70    socializing       0    950  1020
2064756  20151212152498        10      household       0   1095  1105
2064757  20151212152498        10      household       0   1107  1117
2064758  20151212152498         5      household       0   1142  1147
2064759  20151212152498        25      household       0   1147  1172
2064760  20151212152498        53    socializing       0   1207  1260
2064761  20151212152498        15         family       0   1260  1275
2064762  20151212152498       165  entertainment       0   1275     0
2064763  20151212152498       450          sleep       0      0   450

[2064764 rows x 6 columns]

In [27]:
merge = merge.drop(columns=['duration'])
merge

                     id       category  income  start   end
0        20030100013280         sports       1    240   300
1        20030100013280          sleep       1    330   930
2        20030100013280  entertainment       1    930  1080
3        20030100013280         eating       1   1080  1085
4        20030100013280  entertainment       1   1085  1260
5        20030100013280          sleep       1   1260    90
6        20030100013280         sports       1    100   270
7        20030100013352          sleep       1    240   540
8        20030100013352         eating       1    600   630
9        20030100013352       shopping       1    635   695
10       20030100013352      household       1    700   715
11       20030100013352  entertainment       1    715   835
12       20030100013352      household       1    895  1075
13       20030100013352    socializing       1   1075  1115
14       20030100013352         eating       1   1115  1160
15       20030100013352    socializing       1   1160  1340
16       20030100013352      household       1   1340  1400
17       20030100013352          sleep       1   1420   585
18       20030100013848          sleep       0    240   600
19       20030100013848      household       0    600   620
20       20030100013848         family       0    620   625
21       20030100013848      household       0    625   640
22       20030100013848      household       0    660   670
23       20030100013848           work       0    670   790
24       20030100013848      household       0    790   900
25       20030100013848      household       0    900   975
26       20030100013848          sleep       0    975  1050
27       20030100013848      household       0   1050  1065
28       20030100013848         eating       0   1065  1090
29       20030100013848      household       0   1090  1115
...                 ...            ...     ...    ...   ...
2064734  20151212152477         eating       1   1020  1080
2064735  20151212152477          sleep       1   1080  1170
2064736  20151212152477  entertainment       1   1170  1290
2064737  20151212152477         family       1   1320  1322
2064738  20151212152477      household       1   1327     7
2064739  20151212152477         eating       1     22    37
2064740  20151212152477    socializing       1     37   180
2064741  20151212152477  entertainment       1    195   240
2064742  20151212152498          sleep       0    240   360
2064743  20151212152498      household       0    360   375
2064744  20151212152498      household       0    375   380
2064745  20151212152498      household       0    380   381
2064746  20151212152498      household       0    381   382
2064747  20151212152498      household       0    382   387
2064748  20151212152498  entertainment       0    387   447
2064749  20151212152498  entertainment       0    447   507
2064750  20151212152498    socializing       0    507   567
2064751  20151212152498    socializing       0    597   690
2064752  20151212152498    socializing       0    780   900
2064753  20151212152498       shopping       0    905   915
2064754  20151212152498         eating       0    920   950
2064755  20151212152498    socializing       0    950  1020
2064756  20151212152498      household       0   1095  1105
2064757  20151212152498      household       0   1107  1117
2064758  20151212152498      household       0   1142  1147
2064759  20151212152498      household       0   1147  1172
2064760  20151212152498    socializing       0   1207  1260
2064761  20151212152498         family       0   1260  1275
2064762  20151212152498  entertainment       0   1275     0
2064763  20151212152498          sleep       0      0   450

[2064764 rows x 5 columns]

In [28]:
merge.to_csv("merge.csv")

In [30]:
merge[(merge['category'] == 'sleep')]

                     id category  income  start   end
1        20030100013280    sleep       1    330   930
5        20030100013280    sleep       1   1260    90
7        20030100013352    sleep       1    240   540
17       20030100013352    sleep       1   1420   585
18       20030100013848    sleep       0    240   600
26       20030100013848    sleep       0    975  1050
31       20030100013848    sleep       0   1395   405
32       20030100014165    sleep       1    240   300
44       20030100014165    sleep       1   1355   300
45       20030100014169    sleep       0    240   490
56       20030100014169    sleep       0    825   910
71       20030100014169    sleep       0   1340   497
72       20030100014209    sleep       0    240   381
88       20030100014209    sleep       0   1290   381
89       20030100014427    sleep       1    240   300
100      20030100014427    sleep       1   1295   300
101      20030100014550    sleep       1    240   480
114      20030100014550    sleep       1   1275   420
115      20030100014758    sleep       0    240   420
134      20030100014928    sleep       0    240   480
139      20030100014928    sleep       0   1405   650
140      20030100015106    sleep       0    240   540
153      20030100015106    sleep       0   1405   390
154      20030100015322    sleep       0    240   600
173      20030100015322    sleep       0     24   600
174      20030100015390    sleep       1    240   840
180      20030100015390    sleep       1      0   505
181      20030100015490    sleep       1    240   480
200      20030100015490    sleep       1   1350   510
201      20030100015890    sleep       1    240   630
...                 ...      ...     ...    ...   ...
2064583  20151212151905    sleep       0    240   540
2064593  20151212151905    sleep       0   1380   450
2064594  20151212151940    sleep       3    240   360
2064607  20151212151940    sleep       3   1350   360
2064608  20151212151960    sleep       0    240   480
2064615  20151212151960    sleep       0   1380   480
2064616  20151212151989    sleep       1    240   330
2064632  20151212151989    sleep       1   1300  1320
2064633  20151212151989    sleep       1   1320   450
2064634  20151212152019    sleep       2    240   480
2064639  20151212152019    sleep       2   1380   480
2064640  20151212152025    sleep       2    240   480
2064646  20151212152025    sleep       2   1380  1395
2064647  20151212152025    sleep       2   1395   480
2064648  20151212152031    sleep       0    240   540
2064666  20151212152031    sleep       0   1360   570
2064667  20151212152152    sleep       1    240   450
2064674  20151212152152    sleep       1   1320   330
2064680  20151212152155    sleep       0     10   570
2064696  20151212152219    sleep       1   1245   240
2064697  20151212152375    sleep       2    240   390
2064707  20151212152375    sleep       2   1260   390
2064708  20151212152399    sleep       1    240   540
2064717  20151212152399    sleep       1   1385   360
2064718  20151212152468    sleep       3    240   420
2064729  20151212152468    sleep       3   1325   360
2064730  20151212152477    sleep       1    240   600
2064735  20151212152477    sleep       1   1080  1170
2064742  20151212152498    sleep       0    240   360
2064763  20151212152498    sleep       0      0   450

[343392 rows x 5 columns]